#' Generate Topographic Indicators from a Digital Elevation Model
#'
#' @description
#' Generates the following topographic indicators:
#' \itemize{
#'  \item topo_elevation
#'  \item topo_slope: terrain slope in degrees
#'  \item topo_northerness: level of terrain orientation to the north.
#'  \item topo_easterness: level of terrain orientation to the east.
#'  \item topo_tpi: difference between the value of a cell and the mean value of its 8 surrounding cells.
#'  \item topo_tri: Terrain Ruggedness Index is the mean of the absolute differences between the value of a cell and its 8 surrounding cells.
#'  \item topo_roughness: difference between the maximum and the minimum value of a cell and its 8 surrounding cells.
#'  \item topo_flowdir: direction of the greatest drop in elevation, or the smallest rise if all neighbors are higher.
#' }
#' 
#' @param raster (optional, SpatRaster) A "terra" SpatRaster object to be used as a template to crop and resample the Digital Elevation Model. If not provided, topographic indicators are computed for the complete set of tiles available in the `dem` argument. Default: NULL
#' @param dem (required, SpatRaster or path to virtual raster file) Digital Elevation Model generated by [dem_download()] provided as a SpatRaster or as a path to a vrt file. Default: NULL
#' @param indicators (optional, character vector) Names of the topographic indicators to generate. Argument `v` of [terra::terrain]. These names are converted to lowercase and attached the prefix "topo_" in the output raster file. Default: c("slope", "aspect", "TPI", "TRI", "roughness", "flowdir").
#'
#' @return Multilayer SpatRaster object with the selected indicators. If `raster` is provided, then the output object contains all raster layers in `raster` as well.
#' @examples
#' 
#' if(interactive()){
#' 
#'library(dem)
#'library(terra)
#'
#'#subset one county
#'newton <- counties_sf[counties_sf$county == "Newton", ]
#'
#'#download dem tiles for the county
#'dem <- dem_download(
#'  polygon = newton,
#'  resolution = 90,
#'  output = "raster"
#')
#'
#'#plot dem and polygons
#'plot(dem)
#'lines(terra::vect(newton))
#'
#'#compute topographic indicators
#'topography <- dem_indicators(
#'  dem = dem
#')
#'
#'#plot topography
#'plot(topography)
#'
#'}
#' @export
#' @autoglobal
dem_indicators <- function(
    raster = NULL,
    dem = NULL,
    indicators = c(
      "slope", 
      "aspect",
      "TPI", 
      "TRI", 
      "roughness", 
      "flowdir"
    )
){

  if(inherits(x = dem, what = "SpatRaster") == FALSE){
    
    if(file.exists(dem)){
      
      dem <- terra::rast(dem)
      
    } else {
      
      stop("Argument 'dem' must be a SpatRaster or a file name suitable for terra::rast().")
      
    }
    
  }
  
  names(dem) <- "elevation"
  
  
  if(inherits(x = raster, what = "SpatRaster") == TRUE){

    dem <- terra::crop(
      x = dem,
      y = raster
      ) |> 
      terra::resample(y = raster)
    
  } else {
    
    #empty raster, ignored by terra::c()
    raster <- terra::rast()
    
  }
  
  topography <- terra::terrain(
    x = dem,
    v = indicators,
    neighbors = 8
  )

  
  if("aspect" %in% indicators){
    
    northerness <- cos(topography[["aspect"]]* pi / 180)
    names(northerness) <- "northerness"
    
    easterness <- sin(topography[["aspect"]]* pi / 180)
    names(easterness) <- "easterness"
    
    topography <- c(
      topography,
      northerness,
      easterness
    )
    
  }
  
  topography <- c(
    dem,
    topography
  )
  
  names(topography) <- paste0(
    "topo_",
    tolower(names(topography))
  )
  
  c(
    raster,
    topography
    ) |> 
    suppressWarnings()
  
}
